
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { PokemonsProvider } from "@/hooks/usePokemons";

const open_Sans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
      <html lang="en" >
      <body className={`${open_Sans.className} bg-backgroundApp` }>
      <PokemonsProvider>
        {children}
      </PokemonsProvider>
        </body>
      </html>
    
  );
}
